/// UI labels referenced in Assistant FAQ answers that must exist in app code.
///
/// Kept in sync manually when FAQ navigation/settings copy changes.
const List<String> assistantFaqRequiredUiStrings = [
  'Dashboard',
  'Settings',
  'Goals',
  'Achievements',
  'Reward types',
  'Assistant',
  'Accessibility',
  'Appearance',
  'Font size',
  'Dark mode',
  'Rewards & notifications',
  'Goals & sound',
  'Mini-games',
  'Progressive visuals',
  'Customization',
  'Clear Active Goals',
  'Clear Completed Goals',
  'Template Manager',
  'Multi-template',
  'Time-slot goals',
  'Pause Goals',
  'Customize sound effects',
  'Sound effects',
  'Music',
  'Music volume',
  'Preview',
  'Goal creation',
  'Goal completion',
  'Achievement completion',
  'Firefly click',
  'Stone landing',
  'Game failed',
  'Breath click',
  'Breath background',
  'Meteor click',
  'Word Bloom click',
  'Word collected',
  'Zen garden',
  'Cherry blossom',
  'Bonsai garden',
  'Living Canopy',
  'Peace tree',
  'Power tree',
  'Cherry stages 1-3',
  'Cherry Deep Twilight / Aurora',
  'AI Encouragement',
  'Daily Affirmations',
  'Open streak reminders',
  'Color Shop',
  'Customized colours',
  'Theme Preview',
  'Pick Custom Color',
  'OpenDyslexic',
  'Select at least one.',
  'Add plant',
  'Shop',
  'Inventory',
  'Decoration shop',
  'Grow next',
  'To inventory',
  'Skip wait',
  'Sell 1',
  'Select',
  'Selection on',
  'Visit Cherry Blossom Tree',
  'Restart growth',
  'Restart growth from seed',
  'Remove special variant',
  'Confirm before restart growth',
  "Don't ask again",
  'Grow tree',
  'Max tree',
  'Prestige tree',
  'Living Canopy',
  'Bonsai',
  'Bonsai garden',
  'View garden',
  'View tree',
  'Hide menu',
  'Menu',
  'Change path',
  'Peace',
  'Power',
  'Firefly Jar',
  'Stone Balance',
  'Breath Pacer',
  'Meteor Catch',
  'Word Bloom',
  'Rain Catcher',
  'Rain catch',
  'Rain miss',
  'Word Bloom I',
  'Word Bloom II',
  'Word Bloom III',
  'Word Bloom IV',
  'Word Bloom V',
  'Endless Lexicon',
  'Order Streak I',
  'Order Streak II',
  'Order Streak III',
  'Order Streak IV',
  'Order Streak V',
  'Endless Order',
  'Rain Catcher I',
  'Rain Catcher II',
  'Rain Catcher III',
  'Rain Catcher IV',
  'Rain Catcher V',
  'Endless Deluge I',
  'Endless Deluge II',
  'Endless Deluge III',
  'Endless Deluge IV',
  'Endless Deluge V',
  'Endless Deluge VI',
  'Endless Deluge VII',
  'Endless Deluge VIII',
  'Endless Deluge IX',
  'Rain Streak I',
  'Rain Streak II',
  'Rain Streak III',
  'Rain Streak IV',
  'Rain Streak V',
  'Endless Rain Streak',
  'Meteor Shower I',
  'Meteor Shower II',
  'Meteor Shower III',
  'Meteor Shower IV',
  'Endless Skies',
  'Meteor Streak I',
  'Meteor Streak II',
  'Meteor Streak III',
  'Meteor Streak IV',
  'Meteor Streak V',
  'Endless Streak',
  'Inhale',
  'Hold',
  'Exhale',
  'Calm score',
  'End',
  'Settled',
  'Steady',
  'Warming up',
  'Breath complete',
  'Session complete',
  'Drag or tap to aim',
  'Cairn Climber',
  'Endless Summit',
  'Beat the Clock',
  'Duration high score:',
  'Endless high score:',
  'coming soon',
];
